export const origins = [
  "OpenAI", "Google", "Microsoft", "Anthropic", "Meta", "Stability AI",
  "Midjourney", "Hugging Face", "Cohere", "Replicate", "Runway", "Jasper",
  "Vercel", "Independent", "Startup"
];

export const countries = [
  "USA", "Canada", "UK", "Germany", "France", "China", "India", "Japan", "South Korea", "Australia", "Other"
];

export const categoryIcons = {
    "coding": "CodeXml",
    "code generation": "CodeXml",
    "design": "paintbrush",
    "image generation": "Image",
    "text": "FileText-text",
    "text & content": "FileText",
    "data": "ChartNoAxesColumnIncreasing",
    "data analysis": "ChartNoAxesColumnIncreasing",
    "audio": "Music",
    "audio & voice": "Music",
    "chat": "MessageCircle",
    "chatbots": "MessageSquare",
    "video": "Video",
    "video generation": "Video",
    "sql": "Database",
    "sql generation": "Database",
    "automation": "Settings",
    "workflow automation": "Workflow",
    "security": "ShieldCheck",
    "cybersecurity": "ShieldAlert",
    "translation": "Languages",
    "language translation": "Languages",
    "writing": "PenLine",
    "creative writing": "Feather",
    "marketing": "Megaphone",
    "marketing & seo": "TrendingUp",
    "finance": "banknote",
    "finance & trading": "LineChart",
    "gaming": "Gamepad",
    "game development": "Gamepad",
    "legal": "Scale",
    "legal assistance": "Scale",
    "health": "Stethoscope",
    "healthcare & medical": "Stethoscope",
    "education": "book-open",
    "education & learning": "GraduationCap",
    "productivity": "check-circle",
    "customer-support": "Headphones",
    "customer support": "Headset",
    "social-media": "Share",
    "social media tools": "Share",
    "fashion": "Scissors",
    "fashion & style": "Scissors",
    "real-estate": "Home",
    "real estate": "Building2",
    "weather": "CloudSun",
    "weather forecasting": "CloudDrizzle",
    "agriculture": "Sprout",
    "agriculture & farming": "Sprout",
    "travel": "Plane",
    "travel & tourism": "Plane",
    "sports": "dumbbell",
    "sports analytics": "Dumbbell",
    "biology": "dna",
    "biotechnology": "Dna",
    "energy": "Zap",
    "energy & sustainability": "BatteryCharging",
    "entertainment": "Clapperboard",
    "hr": "Users",
    "hr & recruitment": "Briefcase",
    "psychology": "Brain",
    "mental health & wellness": "Smile",
    "blockchain": "Blocks",
    "blockchain & crypto": "Coins",
    "supply-chain": "Truck",
    "supply chain & logistics": "Package",
    "space": "Rocket",
    "space & astronomy": "Telescope",
    "food": "Utensils",
    "food & nutrition": "Pizza",
    "architecture": "Ruler",
    "architecture & design": "Compass",
    "hardware": "Server",
    "hardware development": "Cpu",
    "automation-testing": "Bug",
    "automated testing": "BugPlay"
  };
  
